### ISSUE TITLE
After hook in the test body 

### ISSUE THREAD

**Issue by olikbarabolik** [Shelex/cypress-allure-plugin#118] opened 2022-01-25 10:15 UTC
**Describe the bug**
Step “After” in the test body 

**To Reproduce**
Run script:
describe('Отчет', () => {
after(() => {
    cy.allure().step('Шаг внутри after')
})
})

**Expected behavior**
Steps for after\after all hooks have seporate sections

**Environment (please complete the following information):**
•	Cypress version: 8.7.0
•	Allure plugin version 2.23

![image](https://user-images.githubusercontent.com/62029315/150957766-c8152f8b-27b3-48f0-81fb-f8f78d02c127.png)

**Comment by Shelex** [comment] 2022-01-28 17:18
Hi, @olikbarabolik
Unfortunately I am not able to reproduce it as Allure report giving me proper results for this test code:

```js
describe('Отчет', () => {
    before(() => {
        cy.allure().logStep('шаг внутри before');
    });

    it('test', () => {
        cy.wrap(true).should('be.eq', true);
    });

    after(() => {
        cy.allure().logStep('Шаг внутри after');
    });
});
```
<img width="846" alt="Allure Report 2022-01-28 19-17-14" src="https://user-images.githubusercontent.com/11396724/151592213-074ec325-e597-4967-9936-bcb4f9597051.png">

**Comment by olikbarabolik** [comment] 2022-02-01 14:17
@Shelex version 2.17.2
![image](https://user-images.githubusercontent.com/62029315/151984922-16bbc6f8-29fe-4464-9c3a-6a8c2d734ca1.png)

**Comment by Shelex** [comment] 2022-02-10 09:33
@olikbarabolik 
I agree that steps api in plugin is quite weird, but there is a section in readme describing the difference between step commands. Shortly:

- `step('')` - creates parent step for **current test** (parent means that it could be stopped by next parent step only, or automatically when test\hook finishes)
- `logStep('')` is an alias of `step('', false)` - creates child step for current **parent step**/**hook**/**test**.
- `startStep('')` + `endStep()` - creates step for current **cypress command step** / **step** / **parent step** / **hook** / **test**, so you can nest them in any way by specifying when current step finishes.

So in case you want to create step for afterEach - please use `logStep` instead of `step`, it has quite same behaviour, but could be attached to hook.  Basically `step` command was designed to cover cypress-cucumber-preprocessor steps of test (Given, When, Then) where all other steps will be included.

**Closed** 2022-03-28 22:05 UTC
Labels: bug, needs information
