### ISSUE TITLE
Cannot read property 'addAttachment' of null

### ISSUE THREAD

**Issue by prabhumohan09** [Shelex/cypress-allure-plugin#19] opened 2020-08-28 14:21 UTC
Getting Cannot read property 'addAttachment' of null in before all hook

**Environment (please complete the following information):**
    "@shelex/cypress-allure-plugin": "1.8.0",
    "cypress": "4.1.0",

Windows 10 pro 64 bit OS

**Comment by Shelex** [comment] 2020-08-28 18:23
Hello @prabhumohan09 
Thank you for opening an issue!

The reason is that there is no test available in before all/after all hooks because of [issue#17](https://github.com/Shelex/cypress-allure-plugin/issues/17) . I will add error handling with message for this case. It is how mocha runner is working which cypress uses under the hood.

**Comment by kpittman-securus** [comment] 2020-11-04 22:00
Hi @Shelex - we are also running into this issue, and it's unfortunate because it's masking the true error message in our tests.

We have a complex setup function for our app (not ideal, but it's what we have).

Sometimes if this setup function fails, we cannot see the root cause of the failure due to the Allure plugin throwing this error message.

Could we just have a null check here, and if it is null, then skip the call to `addAttachment`?

![image](https://user-images.githubusercontent.com/62567227/98172278-b1c08f00-1eb6-11eb-91d9-035215470c65.png)

For example, in this screenshot it is almost impossible for us to diagnose the failure, since the `addAttachment of null` masks the original stack trace.

**Comment by Shelex** [comment] 2020-11-05 13:38
@kpittman-securus bit thanks for additional info and pull-request. It is released in v.1.8.4. Could you please check if it solved your issue. As major work regarding hooks handling is currently in progress, btw with no specific estimates.

**Comment by kpittman-securus** [comment] 2020-11-05 16:46
After 1.8.4 we are able to see the true error messages instead of the behavior I outlined above. 🎉

**Closed** 2020-11-06 01:49 UTC
Labels: bug
