### ISSUE TITLE
Cucumber: Allure doesn't resolve Gherkin keywords as steps

### ISSUE THREAD

**Issue by przemdabr** [Shelex/cypress-allure-plugin#186] opened 2023-02-01 23:24 UTC
**Describe the bug**
Allure Reports were not resolving Gherkin keywords as steps. 
Reports are generated but instead of Gherkin keywords as a root there are some strange steps with "then function() {}"

**To Reproduce**
`package.json`
![image](https://user-images.githubusercontent.com/97812658/216186920-d2193ec3-f314-48eb-ab9e-c5ed614726ca.png)

`config.ts`
![image](https://user-images.githubusercontent.com/97812658/216182952-438f5d87-5ee0-4c55-8576-a5fdd6fe2cab.png)
![image](https://user-images.githubusercontent.com/97812658/216183241-1dfc53dd-b6bd-41f6-a39c-3067fe5e73fd.png)

`feature file`
![image](https://user-images.githubusercontent.com/97812658/216183853-e622dc5b-87dd-4618-81a4-ae8509f719ba.png)
`steps`
![image](https://user-images.githubusercontent.com/97812658/216184640-3cf3b622-39b2-432a-94ce-5b9320f8fba4.png)

`Allure report json`
![image](https://user-images.githubusercontent.com/97812658/216185523-16b0bbf0-a257-4b43-b3c1-020716366773.png)

`Allure report`
![image](https://user-images.githubusercontent.com/97812658/216186194-d8c9f944-342d-40e9-b38f-bddcd1997397.png)

**Expected behavior**
Gherkin Keywords should group Cypress steps

**Environment (please complete the following information):**
- Cypress version:  12.5.0                             
- OS: Win 11                                                   

** Developer Tools Console Output **

**Additional context**
I checked many combinations of Cypress ^12 with cypress-cucumber-preprocessor and cypress-allure-plugin, but I'm always getting the same results without grouped steps.

**Comment by AKlavins** [comment] 2023-02-13 07:49
I can also reproduce the same issue. I think it appeared after cypress-cucumber-preprocessor v15.1.0 that added "Log steps and commands using log groups" functionality: https://github.com/badeball/cypress-cucumber-preprocessor/releases/tag/v15.1.0
And the problem is not reproducible with cypress-cucumber-preprocessor v15.0.0

**Comment by MadSandwich** [comment] 2023-03-10 09:52
I also faced this problem. Rollback cypress-cucumber-preprocessor version to 15.0.0 fix this issue for me. Is as per [Closed Issue](https://github.com/badeball/cypress-cucumber-preprocessor/issues/947), they won't fix this on their side. 

@Shelex Is it possible to make a fix on allure plugin side?

**Comment by Shelex** [comment] 2023-03-14 19:03
I guess it is possible, but will require some leisure time which I do not have at the moment in enough capacity.

**Comment by varshanharshank** [comment] 2023-04-27 01:33
@Shelex any update about this ticket

**Comment by Shelex** [comment] 2023-05-01 17:13
@varshanharshank I have invested some time into that, but no "releasable" outcome yet.

**Comment by Shelex** [comment] 2023-05-08 15:50
@przemdabr @samixchoumi @MadSandwich @jzaratei @Krivega @AKlavins @varshanharshank 

Version v2.39.0 is released where I can see gherkin steps handled properly for my [example report](https://shelex.github.io/cypress-allure-plugin-example/58/#suites/81715fe1ee14b249dfa611b19bc11d91/636763acb7bebec/)

Please let me know if this is still an issue for you.

**Comment by MadSandwich** [comment] 2023-05-09 10:55
@Shelex everything is good for me, thanks for your help!

**Comment by AKlavins** [comment] 2023-05-10 08:10
Thanks you @Shelex , looking good for me as well!

**Comment by samixchoumi** [comment] 2023-05-10 08:12
Hello @Shelex, it seem to works fine for us too (and with cucumber preprocessor uptodate too 👍)

**Comment by Shelex** [comment] 2023-05-10 23:38
As no negative feedback regarding the fix is received, closing the issue.

**Closed by Shelex** 2023-05-10 23:38 UTC
Labels: bug
